const fakePodcasts = [
    {
      id: 1,
      baner: '/images/tehnologija.jpg',
      naziv: 'Podkast o tehnologiji',
      opis: 'Podkast koji istražuje najnovije tehnologije i inovacije u industriji.',
      kategorija: 'Tehnologija',
      kreator: 'Marko Marković',
      isFavorite: true,
      epizode: [
        {
          id: 1,
          naziv: 'Epizoda 1: AI i budućnost',
          datum: '2025-01-15T10:00:00',
          url: 'https://example.com/podcasts/epizoda1.mp3',
        },
        {
          id: 2,
          naziv: 'Epizoda 2: 5G i njegove prednosti',
          datum: '2025-01-22T10:00:00',
          url: 'https://example.com/podcasts/epizoda2.mp3',
        },
      ],
    },
    {
      id: 2,
      baner: '/images/putovanja.jpg',
      naziv: 'Podkast o putovanjima',
      opis: 'Priče sa putovanja po svetu, sa savjetima i iskustvima.',
      kategorija: 'Putovanja',
      kreator: 'Ana Petrović',
      isFavorite: true,
      epizode: [
        {
          id: 1,
          naziv: 'Epizoda 1: Tajne Japana',
          datum: '2025-02-01T12:00:00',
          url: 'https://example.com/podcasts/epizoda1.mp3',
        },
        {
          id: 2,
          naziv: 'Epizoda 2: Rajske plaže Kariba',
          datum: '2025-02-08T12:00:00',
          url: 'https://example.com/podcasts/epizoda2.mp3',
        },
      ],
    },
    {
      id: 3,
      baner: '/images/zdravlje.jpg',
      naziv: 'Podkast o zdravlju',
      opis: 'Sve o zdravlju, ishrani i fizičkoj aktivnosti.',
      kategorija: 'Zdravlje',
      kreator: 'Jovana Kovačević',
      isFavorite: false,
      epizode: [
        {
          id: 1,
          naziv: 'Epizoda 1: Zdrava ishrana u 2025. godini',
          datum: '2025-03-10T14:00:00',
          url: 'https://example.com/podcasts/epizoda1.mp3',
        },
        {
          id: 2,
          naziv: 'Epizoda 2: Kako vežbati kod kuće',
          datum: '2025-03-17T14:00:00',
          url: 'https://example.com/podcasts/epizoda2.mp3',
        },
      ],
    },
    {
      id: 4,
      baner: '/images/istorija.jpg',
      naziv: 'Podkast o istoriji',
      opis: 'Priče iz prošlosti koje su oblikovale naš svet.',
      kategorija: 'Istorija',
      kreator: 'Nikola Petrović',
      isFavorite: false,
      epizode: [
        {
          id: 1,
          naziv: 'Epizoda 1: Rim - grad na sedam brda',
          datum: '2025-04-01T15:00:00',
          url: 'https://example.com/podcasts/epizoda1.mp3',
        },
        {
          id: 2,
          naziv: 'Epizoda 2: Kraljevina Jugoslavija',
          datum: '2025-04-08T15:00:00',
          url: 'https://example.com/podcasts/epizoda2.mp3',
        },
      ],
    },
    {
      id: 5,
      baner: '/images/film.jpg',
      naziv: 'Podkast o filmu',
      opis: 'Analize filmova, industrije i noviteta iz sveta kinematografije.',
      kategorija: 'Film',
      kreator: 'Marko Marković',
      isFavorite: false,
      epizode: [
        {
          id: 1,
          naziv: 'Epizoda 1: Najbolji filmovi 2024. godine',
          datum: '2025-05-01T16:00:00',
          url: 'https://example.com/podcasts/epizoda1.mp3',
        },
        {
          id: 2,
          naziv: 'Epizoda 2: Trilogija Gospodara prstenova',
          datum: '2025-05-08T16:00:00',
          url: 'https://example.com/podcasts/epizoda2.mp3',
        },
      ],
    },
    {
      id: 6,
      baner: '/images/muzika.jpg',
      naziv: 'Podkast o muzici',
      opis: 'Pregled muzičkih žanrova, novih izvođača i hitova.',
      kategorija: 'Muzika',
      kreator: 'Ivana Milenković',
      isFavorite: true,
      epizode: [
        {
          id: 1,
          naziv: 'Epizoda 1: Nova muzika iz Srbije',
          datum: '2025-06-01T17:00:00',
          url: 'https://example.com/podcasts/epizoda1.mp3',
        },
        {
          id: 2,
          naziv: 'Epizoda 2: Osvrt na pop kulturu',
          datum: '2025-06-08T17:00:00',
          url: 'https://example.com/podcasts/epizoda2.mp3',
        },
      ],
    },
    {
      id: 7,
      baner: '/images/ekonomija.jpg',
      naziv: 'Podkast o ekonomiji',
      opis: 'Diskusije o ekonomskim pitanjima i globalnim tržištima.',
      kategorija: 'Ekonomija',
      kreator: 'Marko Marković',
      isFavorite: true,
      epizode: [
        {
          id: 1,
          naziv: 'Epizoda 1: Posledice inflacije',
          datum: '2025-07-01T18:00:00',
          url: 'https://example.com/podcasts/epizoda1.mp3',
        },
        {
          id: 2,
          naziv: 'Epizoda 2: Ekonomija u 2025. godini',
          datum: '2025-07-08T18:00:00',
          url: 'https://example.com/podcasts/epizoda2.mp3',
        },
      ],
    },
    {
      id: 8,
      baner: '/images/politika.jpg',
      naziv: 'Podkast o politici',
      opis: 'Aktuelni politički događaji i analize.',
      kategorija: 'Politika',
      kreator: 'Aleksandar Stanković',
      isFavorite: false,
      epizode: [
        {
          id: 1,
          naziv: 'Epizoda 1: Predsednički izbori 2025',
          datum: '2025-08-01T19:00:00',
          url: 'https://example.com/podcasts/epizoda1.mp3',
        },
        {
          id: 2,
          naziv: 'Epizoda 2: Evropska unija i Srbija',
          datum: '2025-08-08T19:00:00',
          url: 'https://example.com/podcasts/epizoda2.mp3',
        },
      ],
    },
    {
      id: 9,
      baner: '/images/sport.jpg',
      naziv: 'Podkast o sportu',
      opis: 'Aktuelnosti iz sveta sporta, analiza mečeva i intervjui sa sportistima.',
      kategorija: 'Sport',
      kreator: 'Luka Kostić',
      isFavorite: true,
      epizode: [
        {
          id: 1,
          naziv: 'Epizoda 1: Fudbalske lige 2025',
          datum: '2025-09-01T20:00:00',
          url: 'https://example.com/podcasts/epizoda1.mp3',
        },
        {
          id: 2,
          naziv: 'Epizoda 2: Olimpijske igre 2025',
          datum: '2025-09-08T20:00:00',
          url: 'https://example.com/podcasts/epizoda2.mp3',
        },
      ],
    },
    {
      id: 10,
      baner: '/images/nauka.jpg',
      naziv: 'Podkast o nauci',
      opis: 'Razgovori o naučnim otkrićima, istraživanjima i budućim tehnologijama.',
      kategorija: 'Nauka',
      kreator: 'Dragana Zdravković',
      isFavorite: false,
      epizode: [
        {
          id: 1,
          naziv: 'Epizoda 1: Genetika i biotehnologija',
          datum: '2025-10-01T21:00:00',
          url: 'https://example.com/podcasts/epizoda1.mp3',
        },
        {
          id: 2,
          naziv: 'Epizoda 2: Osvrt na Mars misiju',
          datum: '2025-10-08T21:00:00',
          url: 'https://example.com/podcasts/epizoda2.mp3',
        },
      ],
    },
  ];
  
  export default fakePodcasts;
  